### ISSUE TITLE
Create the basic structure of FE

### ISSUE THREAD

**Issue by Venus-Izadi** [openpracticelibrary/opl-fe#12]
USER NEED:
As a dev, I need the base code for Front End, so that I can start contributing.

NOTES:
We chose to use React.js and Material UI.

**Comment by jameshbarton** [comment]
Updated README to include installing package dependencies.
https://github.com/openpracticelibrary/opl-fe/commit/40e53ce0b981a36fa56f4611bc626655a27fb5c4
