### ISSUE TITLE
[SPIKE] AMA Featureset - StackExchange API

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-fe#126]
Explore the possibility of using the StackExchange API as a "backend" for the AMA feature in OPL. This spike is **not** concerned with the display of AMA in opl-fe, only with the ability to store and track questions and answers in opl-content-api.

**ASSUMPTIONS**
- Questions can be added to StackExchange via the API, reference stored in opl-content-api
- Answers to questions can be added via API, reference stored in opl-content-api
- Answers submitted on StackExchange can be stored by reference as well in opl-content-api.

**QUESTIONS**
- How might we track answers submitted via StackExchange interface and not via OPL?
- Any cost considerations or API limits?
- What do the requisite API calls look like and how many are there to retrieve the data necessary?
- How might we specify the specific StackExchange board (i.e. StackOverflow, pm.stackexchange..., etc) where questions should be posed?
- Any concerns around StackExchange currency needed to do things like upvote and comment?

**ACCEPTANCE CRITERIA**
- The output of this Spike should be a write-up, answering the questions above, challenging any assumptions where necessary, providing context around assumptions where necessary, and providing at least one suggestion about how we should proceed. Link that write up in the comments of this issue, and there should another ticket opened to discuss the suggestion(s) and define our path forward.

**NOTES**
- See Mural:
https://app.mural.co/t/warhw2023/m/warhw2023/1591711845290/450d2673d68ef81a7411b05fadbf3073aa5bbcc0

**Comment by jameshbarton** [comment]
See the write-up here:  https://docs.google.com/document/d/1OiwIw3u1LghEXUWCmr5xbO_SUwZsdE1eKbv2op30uFk/edit?usp=sharing

Created ticket openpracticelibrary/opl-docs/issues#118 to track the follow-up decision.
