### ISSUE TITLE
Practice Page - Visual Design Refinements

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#131]
**NOTES**
- Logged out layout: https://zpl.io/aXxMv5P
- Reorder Links and AMA
- Add Subsections 'Practice Steps' & 'Facilitation Tips' to How to
- Include sticky nav functionality - persistent at top of page

**Comment by lallmon** [comment]
Couple notes before I forget for next discussion
- Layout link is broken
- Typically we need to extract any _functionality_ into it's own story.

**Comment by omcneil** [comment]
No longer needed
