### ISSUE TITLE
v1 About Page - Navigation + Visual Design (3)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#133]
As Nova, I need to know more more about OPL so that I can make a decision on using it. 

**ACCEPTANCE CRITERIA**
**Given** I am on any page of the site
**When** I click on the Left Nav or footer link or Landing page button
**Then** I am navigated to an About Page of static content and the copy or photos is included.

**NOTES**
- Connect with Marketing for copy
- See visual design mockup - https://zpl.io/a8g9QKE
- Mobius video: https://www.youtube.com/watch?v=N4mBIZg8MnQ&list=PLkg9jnMh6bhd0avDugIM81BU9VkBEaMMz
- Join OPL Slack: https://join.slack.com/t/openpracticelibrary/shared_invite/zt-ert9npro-cA~mzDL2yrOSbRrjmtoRSw
- User feedback bottom of page cta - https://forms.gle/nXCvPEkjx6VdF6Px6

**BLOCKERS**
- Some copy is work in progress but layout is set to go with placeholder
- Google form for user feedback is a work-in-progress but that shouldn't slow dev

**Comment by omcneil** [comment]
link to join OPL Slack - https://join.slack.com/t/openpracticelibrary/shared_invite/zt-ert9npro-cA~mzDL2yrOSbRrjmtoRSw

**Comment by jameshbarton** [comment]
About page and associated drawer and footer links active in dev now.
http://openpracticelibrary-opl-dev.apps.s44.core.rht-labs.com/about

<img width="1368" alt="Screen Shot 2020-07-03 at 8 44 11 AM" src="https://user-images.githubusercontent.com/52334260/86470576-b2c79100-bd09-11ea-8754-c332a484504f.png">
