### ISSUE TITLE
Navigation Components (3)

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-fe#14]
As Nova, I need to be able to navigate the OPL application through a left drawer which automatically opens when I leave the home page and includes various ways to see more information. I also need to be able to see a breadcrumb on a particular Practice page for sections of the Mobius loop and tags plus I have access to important pages from the footer with social channel links.

**ACCEPTANCE CRITERIA** 

Left Drawer
**Given** I am on the All Practices or Practice page and the drawer is open
**When** I can click on ways to navigate the site or external links
**Then** I can navigate to more information 
**And** I if I click the icon the drawer will collapse.

Breadcrumb
**Given** I am on a Practice page
**When** I can see a breadcrumb of where the particular practice fits in the Tag and Mobius loop
**Then** I can click backwards to access the All Practices page 
**And** the content is pre-filtered by Tag and/or Mobius loop. 

**NOTES**
- Drawer expanded - https://zpl.io/aXAMoxP (By mobius loop toggled open by default)
- By mobius loop toggle - https://zpl.io/2GJQYZY
- Drawer collapsed - https://zpl.io/2yvzJRJ

**Comment by omcneil** [comment]
- [ ] test

**Comment by heyjerrybecker** [comment]
Moving back to "to do" in order to encompass including temporary logo and shadow at top of drawer
