### ISSUE TITLE
Setup Cypress E2E Testing as part of CI Workflow (5)

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-fe#144]
Goals:

Create necessary tekton tasks to run cypress E2E test after argo deploys to dev
Add to OPL-CD repo
Trigger argo sync to staging after E2E tests pass
Ticket is complete when all infrastructure is deployed and successfully running one test through the full pipeline. Next step as a separate ticket will be to create user flows for testing.

As _______ (app), I need _______ (value), so that I can _______ (problem / task solved).

- Acceptance Criteria
**Given** I...
**When** I... 
**Then** I...
**And** I... (if needed)

- Notes

- Add Blockers

***OTHER:***

**Comment by haithamshahin333** [comment]
Goals:
1. Create necessary tekton tasks to run cypress E2E test after argo deploys to dev
2. Add to OPL-CD repo
3. Trigger argo sync to staging after E2E tests pass

Ticket is complete when all infrastructure is deployed and successfully running one test through the full pipeline. Next step as a separate ticket will be to create user flows for testing.
