### ISSUE TITLE
Like Functionality in Practice Card(1)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#16]
As Nova, I need to know how popular a piece of content is and add to its popularity from every place a practice is featured so that I can decide if it is something I want to know more about.  

**ACCEPTANCE CRITERIA** 

**Given** I am viewing a practice thumbnail from any page of the app or am on a particular practice page it's self
**When** I view the Like icon
**Then** I see a counter next to it with number of Likes
**And** I can add a Like to increase that number.

**NOTES**
- See All Practices thumbnail hover https://zpl.io/br54PB3
- See collection design https://zpl.io/2GJQYZY
- See like added https://zpl.io/2yvzJRJ
- Collection story: https://github.com/openpracticelibrary/opl-fe/issues/17

**Comment by Venus-Izadi** [comment]
<Blocked> 
We don't have a practice thumbnail page yet. 
The Like functionality has been covered in ticket #17
