### ISSUE TITLE
Spike - Netlify Deep Dive

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-fe#184]

**Comment by jameshbarton** [comment]
Part of the Netlify deep dive spike is to evaluate alternatives for AMA management.  Here is the initial draft of my [recommendations](https://docs.google.com/document/d/1tWIKwW0UPDuUB8qkPjBx6o5f5yNWz24rcRo5lNq2Gls/edit#).

**Comment by shaheinm** [comment]
And for the hosting/architecture/maintenance/cost considerations, here is my [initial draft](https://docs.google.com/document/d/1YOEhoHgRKePJpoyN09_zlVXqR5V-Go_FlGTapX7zcR0/edit#)
