### ISSUE TITLE
Filter practices by keyword search (3)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#63]
As Nova, I need to be able to search practices by keywords, so that I may view relevant practices to my current need.

**ACCEPTANCE CRITERIA**
**Given** I am on the all practices page 
**When** I choose to search practices
**Then** Practices should be filtered based on the keyword(s) typed into the search box

**NOTES**
- For v1, this may be just a simple title, subtitle, and tags search.
- If backend implementation of search on markdown fields is available, then it should be added.
- For v1, probably a type your search, and click a button to search interaction is warranted. If live filtering is desired (as you type), Apollo can support it, but it will require a lot of data being pulled in on the all practices page. Creating an indexing service is a much better way of implementing an as-you-type sort of search filter, and that's not part of our v1.
- See openpracticelibrary/opl-content-api#31
- See designs - https://zpl.io/VKRqYkE

**BLOCKERS**
- None

**Comment by lallmon** [comment]
Notes:
- Hitting ENTER will trigger filter.
- Will clear current filters and search all practices
