### ISSUE TITLE
Sort practices by curated field (popularity) (1)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#64]
As Nova, I need to view practices by popularity, so that I can get the most out of my visit to the Open Practice Library.

**ACCEPTANCE CRITERIA**
**Given** I have chosen to sort practices by popularity
**When** I view the practice list
**Then** I should see practices sorted by popularity from most to least

**NOTES**
- Use a `curated` integer field, sorted in ascending order, to determine the popularity
- Relates to openpracticelibrary/opl-content-api#22

**BLOCKERS**
- None

**Comment by jameshbarton** [comment]
Here's a GraphQL query showing how to do this with new Practices  curated field.

<img width="1342" alt="Screen Shot 2020-06-05 at 9 52 04 AM" src="https://user-images.githubusercontent.com/52334260/83884648-2e3a2080-a713-11ea-9bdc-1dd46c9dc9f3.png">

**Comment by shaheinm** [comment]
Piyush is out for the next couple of days, progress on this can be continued here - https://github.com/openpracticelibrary/opl-fe/tree/filter-bar-all-practices-page
