### ISSUE TITLE
Filter practices by Discipline

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#66]
As Nova, I need to filter content by the discipline I am most comfortable or by that which I aspire for, so that I am learning what is relevant to me. 

**ACCEPTANCE CRITERIA**
**Given** I am on the Home - All Practices page
**When** toggle the filter menu open
**Then** I have a filter menu option for 'By Discipline'
**And** I open that menu I see five options including 'All the roles'
**And** I can scroll within the menu for additional options.

**NOTES**
- The layout of this structure is defined
- See design of menus - https://zpl.io/VKRqYkE
- See Discipline menu open - https://zpl.io/2ENe3el
- Drop down options: 
#Engineering
#ProductManager
#Designer 
#ScrumMaster
#ProjectManager
#Researcher 
#ProjectManager
#AgileCoach
#BusinessAnalyst 

**BLOCKERS**

**Comment by omcneil** [comment]
Closing issue, no longer needed
