### ISSUE TITLE
Ability to Play Video in Multimedia Gallery (3)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#67]
As Nova, I need the ability to play a video associated with a practice in the media gallery, so that I can better understand the content.

**ACCEPTANCE CRITERIA**

**Given** I am on a practice page
**When** a video is present in the media gallery section
**Then** I should be able to play the video in place

**NOTES**
- None

**BLOCKERS**
- None

**Comment by Venus-Izadi** [comment]
We're using react-image-gallery library to show images and videos. [[DEMO](https://www.linxtion.com/demo/react-image-gallery/)]

This is the source code, we can refer to include the video: https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js
