### ISSUE TITLE
Tech Debt: Unit and Integration Testing

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-fe#69]
As a system, we need appropriate coverage for unit and integration tests, so that changes and new features can be confirmed as non-breaking, or so that the team is aware of breaking changes.

**ACCEPTANCE CRITERIA**

**Given** A pull request is submitted
**When** the pull request is reviewed
**Then** all new code has commensurate tests written before approval
**And** all existing code that is modified has updated tests where necessary

**NOTES**
- Let's shoot for 80% coverage of unit tests across all of our repositories to start
- This is in the `opl-fe` repo for visibility, but it applies to all of our repositories

**BLOCKERS**
None

**Comment by omcneil** [comment]
no longer needed
