### ISSUE TITLE
Footer for all pages (1)

### ISSUE THREAD

**Issue by piyushsn** [openpracticelibrary/opl-fe#74]
As a Nova, I need to have access to various sections of OPL from the bottom of the page so that I can always access practices and other details of the site. 

Footer
**Given** I am on any page of the app
**When** I can access footer pages and external links
**Then** I see ways to navigate the site
**And** I can click on external links.

NOTES:
- See global footer in Home Page design here - https://zpl.io/aBJ4L0m
- Assets are in Zeplin for download please use the colored Labs logo
- Email link (TBD) please ping @heyjerrybecker to determine
- External links include: 
Podcast https://podcasts.apple.com/us/podcast/open-practice-podcast/id1501715186
Insta https://www.instagram.com/openpracticelibrary/?hl=en
Git https://github.com/openpracticelibrary
YT https://www.youtube.com/channel/UCBGbB7xVsmf-yQ8NXn7TOVg?view_as=subscriber

![Screen Shot 2020-05-29 at 11 53 19 AM](https://user-images.githubusercontent.com/22623602/83294940-068f0980-a1a3-11ea-9b47-5eeb6796901e.png)

BLOCKERS:
No

**Comment by omcneil** [comment]
Need to add social links

**Comment by Venus-Izadi** [comment]
This component is partially done.

**Remaining work**
- Adding logos and links
- Add space between links

**Comment by heyjerrybecker** [comment]
Lemme create one real quick and I'll get the info over to ya
It'll be "info@openpracticelibrary.com"

**Comment by heyjerrybecker** [comment]
@piyushsn 
done - info@openpracticelibrary.com
