### ISSUE TITLE
Set up React app with Apollo 

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-fe#9]
As Nova, I need a web application/user interface, so that I can engage with the Open Practice Library.

ACCEPTANCE CRITERIA (as persona):
**Given** I want to engage with OPL,
**When** I browse to the OPL URL,
**Then** I expect to see OPL content displayed

NOTES:
- Set up Apollo (GraphQL client) in a React application
- No UI/UX/design components necessary in this issue - simply display any data retrieved on a blank page.

BLOCKERS:
- [API Gateway](https://github.com/openpracticelibrary/opl-api-gateway/issues/1) should be created first.

**Comment by shaheinm** [comment]
Start [here](https://www.apollographql.com/docs/react/)
